[build]
builder = "nixpacks"

[deploy]
startCommand = "chmod +x start.sh && ./start.sh"
# healthcheckPath = "/"
# healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.envs]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://0.0.0.0:$PORT"

# Database configuration (if using external database)
# DATABASE_CONNECTION_STRING = "your-database-connection-string"

# CORS settings for production
CORS_ALLOWED_ORIGINS = "*"

# WebSocket configuration
WEBSOCKET_ENABLED = "true"

# Security headers
ASPNETCORE_FORWARDEDHEADERS_ENABLED = "true"

# Performance settings
ASPNETCORE_Kestrel__Limits__MaxConcurrentConnections = "100"
ASPNETCORE_Kestrel__Limits__MaxConcurrentUpgradedConnections = "100"

# Debug settings
ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS = "true"
ASPNETCORE_LOGGING__LOGLEVEL__DEFAULT = "Information"
ASPNETCORE_LOGGING__LOGLEVEL__MICROSOFT = "Information" 